### PR TITLE
Responsive Kokorobot portfolio

### PR DESCRIPTION
**Pull request by friederjanmoerman**
Hi,

I made your portfolio responsive. All changes have been put at the bottom of your css file to keep it clean. I tried to adapt my coding style to your way of working.
This isn't how I usually write html or css. You might want to check out my blank website template which puts out linted and minified code: https://github.com/friederjanmoerman/ez 
I would also advise looking into sass (nesting, reusable blocks of code and more): https://sass-lang.com/
I would also advise looking into building maintainable and scalable code as I noticed you haven't been using classes a lot, but rather referred to the elements themselves in your stylesheet:
— BEM or block element modifier: http://getbem.com/
— SMACCS or scalable and modular architecture for css: https://smacss.com/

For your meta, most of the time  `<meta name="viewport" content="width=device-width, initial-scale=1.0">` is used. This leads to a website displaying at its original size. The way to go to start making your website responsive.

Friendly regards <3

### CODE REVIEW

**Comment by neauoire** [comment]
Before merging, would you mind formatting your CSS following the current style of the project?

**Comment by friederjanmoerman** [comment]
Putting each rule in one line?
I can also minify the whole thing if you like?

**Comment by neauoire** [comment]
Don't minify, it's hard to read :)
Just on one line, with a trailing space after `{` and before `}`.
<3

**Comment by neauoire** [comment]
Thanks Frider! That's excellent 👍

**Comment by friederjanmoerman** [comment]
If you have any questions or need any advise front-end related, just hit me up.
Peace out ✌️

**Comment by rekkabell** [comment]
Omg, you’re a lifesaver. Thank you so much :>

**Pull request merged**
